ASVP/Controllers/OperacaoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ASVP.Models;

namespace ASVP.Controllers
{
    public class OperacaoController : Controller
    {
        private AsiloEntities db = new AsiloEntities();

        //
        // GET: /Operacao/

        public ActionResult Index()
        {
            try
            {
                if (VerificaLoginOperacao())
                {
                    ViewBag.idDestino = new SelectList(db.DESTINO, "idDestino", "descricao");
                    return View(db.OPERACAO.OrderBy(p => p.descricao).ToList());
                    
                }
                else
                {
                    TempData["alertMessage"] = "Você precisa de permissão para acessar a tela de operações.";
                    return RedirectToAction("Index", "Home", TempData["alertMessage"]);
                }

            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
                return View();

            }
            
        }

        //
        // GET: /Operacao/Details/5

        public ActionResult Details(int id)
        {
            try
            {
                if (VerificaLoginOperacao())
                {
                    OPERACAO operacao = db.OPERACAO.Find(id);
                    if (operacao == null)
                    {
                        return HttpNotFound();
                    }
                    return View(operacao);
                }
                else
                {
                    TempData["alertMessage"] = "Você precisa de permissão para acessar a tela de operações.";
                    return RedirectToAction("Index", "Home", TempData["alertMessage"]);
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
                return View();

            }
            
        }

        //
        // GET: /Operacao/Create

        public ActionResult Create()
        {
            if (VerificaLoginOperacao())
            {
                ViewBag.idDestino = new SelectList(db.DESTINO, "idDestino", "descricao");
                return View();
            }
            else
            {
                TempData["alertMessage"] = "Você precisa de permissão para acessar a tela de operações.";
                return RedirectToAction("Index", "Home", TempData["alertMessage"]);
            }
        }

        //
        // POST: /Operacao/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(OPERACAO operacao)
        {
            try
            {
                if (VerificaLoginOperacao())
                {
                    if (ModelState.IsValid)
                    {

                        if (Request.Form["Sim"] != null)
                        {
                            operacao.idoso = "S";
                        }
                        else
                        {
                            if (Request.Form["Nao"] != null)
                            {
                                operacao.idoso = "N";
                            }
                            
                        }
                        
                        operacao.descricao = operacao.descricao.ToUpper();
                        db.OPERACAO.Add(operacao);
                        db.SaveChanges();
                        if (Request.Form["Salvar+"] != null)
                        {

                            Response.Redirect("Create");
                        }
                        else
                        {
                            return RedirectToAction("Index");
                        }
                    }

                    return View(operacao);
                }
                else
                {
                    TempData["alertMessage"] = "Você precisa de permissão para acessar a tela de operações.";
                    return RedirectToAction("Index", "Home", TempData["alertMessage"]);
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
                return View(operacao);

            }
           
        }

        //
        // GET: /Operacao/Edit/5

        public ActionResult Edit(int id)
        {
            try
            {
                if (VerificaLoginOperacao())
                {
                    OPERACAO operacao = db.OPERACAO.Find(id);
                    
                    if (operacao == null)
                    {
                        return HttpNotFound();
                    }
                    return View(operacao);
                }
                else
                {
                    TempData["alertMessage"] = "Você precisa de permissão para acessar a tela de operações.";
                    return RedirectToAction("Index", "Home", TempData["alertMessage"]);
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
                return View();

            }
            
        }

        //
        // POST: /Operacao/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(OPERACAO operacao)
        {
            try
            {
                if (VerificaLoginOperacao())
                {
                    if (ModelState.IsValid)
                    {

                        if (Request.Form["Sim"] != null)
                        {
                            operacao.idoso = "S";
                        }
                        else
                        {
                            if (Request.Form["Nao"] != null)
                            {
                                operacao.idoso = "N";
                            }

                        }
                        
                        operacao.descricao = operacao.descricao.ToUpper();
                        db.Entry(operacao).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    return View(operacao);
                }
                else
                {
                    TempData["alertMessage"] = "Você precisa de permissão para acessar a tela de operações.";
                    return RedirectToAction("Index", "Home", TempData["alertMessage"]);
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
                return View(operacao);

            }
            
            
        }

        //
        // GET: /Operacao/Delete/5

        public ActionResult Delete(int id)
        {
            try
            {
                if (VerificaLoginOperacao())
                {
                    OPERACAO operacao = db.OPERACAO.Find(id);
                    if (operacao == null)
                    {
                        return HttpNotFound();
                    }
                    return View(operacao);
                }
                else
                {
                    TempData["alertMessage"] = "Você precisa de permissão para acessar a tela de operações.";
                    return RedirectToAction("Index", "Home", TempData["alertMessage"]);
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
                return View();

            }
           
        }

        //
        // POST: /Operacao/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                if (VerificaLoginOperacao())
                {
                    OPERACAO operacao = db.OPERACAO.Find(id);
                    db.OPERACAO.Remove(operacao);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["alertMessage"] = "Você precisa de permissão para acessar a tela de operações.";
                    return RedirectToAction("Index", "Home", TempData["alertMessage"]);
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
                return View();

            }
            
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public bool VerificaLoginOperacao()
        {

            if (Request.Cookies["usuarioAsilo"] != null)
            {
                int id = Convert.ToInt32(Request.Cookies["usuarioAsilo"].Value.ToString().Replace("usuarioAsilo=", ""));
                if (db.ADMINISTRADOR.Find(id).cadOperacao == "S")
                    return true;
                else return false;
            }
            else
            {
                return false;

            }
        }
    }
}

ASVP/Views/Operacao/Create.cshtml
@model ASVP.Models.OPERACAO
@{
    ViewBag.Title = "Cadastro de Operação";
}

<script type="text/javascript">
    $(document).ready(function () { $("#descricao").addClass("text-uppercase"); });
    $('#myModal').on('shown.bs.modal', function () {
        $('#btSim').focus();
    })
</script>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Nova Operação</h3>
    </div>
    <div class="panel-body">

        @if (ViewBag.Msg != null)
        {
            <div class="alert alert-danger">
                <strong>Atenção!</strong> @ViewBag.Msg
            </div>
        }
        <br />
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <form>
                <fieldset>
                    <legend>OPERACAO</legend>
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="editor-label">
                                @Html.LabelFor(model => model.descricao)
                            </div>
                            <div class="editor-field">
                                @Html.EditorFor(model => model.descricao)
                                @Html.ValidationMessageFor(model => model.descricao)
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="editor-label">
                                @Html.LabelFor(model => model.tipo)
                            </div>
                            <div class="editor-field">
                                @Html.DropDownListFor(model => model.tipo, new List<SelectListItem>
                                {
                                    new SelectListItem {Text = "Crédito", Value = "C"},
                                    new SelectListItem {Text = "Débito", Value = "D"}
                                }, new { @class = "form-control", style = "width: 180px" })
                                @Html.ValidationMessageFor(model => model.tipo)
                            </div>
                        </div>
                        

                        </div>
                    <br />
                    <p>
                        <input type="button" name="Salvar" class="btn btn-primary" value="Salvar" data-toggle="modal" data-target="#myModal"/> | @Html.ActionLink("Voltar", "Index", null, new {@class = "btn btn-primary", type = "button"})
                    </p>
                    <div class="modal fade" tabindex="-1" role="dialog" id="myModal">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title">ATENÇÃO</h4>
                                </div>
                                <div class="modal-body">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <span>Para esta operação, será necessário informar o idoso no lançamento de movimentos ?</span>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-2">
                                        </div>
                                        <div class="col-md-2">
                                        </div>
                                    </div>
                                </div>
                            <br />
                                <div class="modal-footer">


                                    <input type="submit" name="Sim" class="btn btn-primary" value="Sim" />
                                    <input type="submit" name="Nao" class="btn btn-primary" value="Não" />



                                </div>
                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div><!-- /.modal -->
                </fieldset>
            </form>
            

        }


    </div>
</div>




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ASVP/Views/Operacao/Delete.cshtml
@model ASVP.Models.OPERACAO

@{
    ViewBag.Title = "Delete";
}

<h2>Tem certeza que deseja apagar a operação @Html.DisplayFor(model => model.descricao) ?</h2>

<br />
@if (ViewBag.Msg != null)
{
    <div class="alert alert-danger">
        <strong>Atenção!</strong> @ViewBag.Msg
    </div>
}
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
   <p>
            <input type="submit" value="Sim" class="btn btn-primary" /> |
            @Html.ActionLink("Não", "Index", null, new { @class = "btn btn-primary" })
        </p>
    
    <div class="visibilidade">
                @Html.DisplayNameFor(model => model.id_operacao)
            </div>
            <div class="visibilidade">
                @Html.DisplayFor(model => model.id_operacao)
            </div>
}

ASVP/Views/Operacao/Details.cshtml
@model ASVP.Models.OPERACAO

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>OPERACAO</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.id_operacao)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.id_operacao)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.descricao)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.descricao)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.tipo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.tipo)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Editar", "Edit", new { id=Model.id_operacao }) |
    @Html.ActionLink("Voltar", "Index")
</p>

ASVP/Views/Operacao/Edit.cshtml
@model ASVP.Models.OPERACAO

@{
    ViewBag.Title = "Edit";
}
<script type="text/javascript">
    $(document).ready(function () { $("#descricao").addClass("text-uppercase"); });
    $('#myModal').on('shown.bs.modal', function () {
        $('#btSim').focus();
    })
</script>


<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Alteração de Operação</h3>
    </div>
    <div class="panel-body">
        @if (ViewBag.Msg != null)
        {
            <div class="alert alert-danger">
                <strong>Atenção!</strong> @ViewBag.Msg
            </div>
        }

        <br />
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <form>
                <fieldset>
                    <legend>OPERACAO</legend>
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="editor-label">
                                @Html.LabelFor(model => model.descricao)
                            </div>
                            <div class="editor-field">
                                @Html.EditorFor(model => model.descricao)
                                @Html.ValidationMessageFor(model => model.descricao)
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="editor-label">
                                @Html.LabelFor(model => model.tipo)
                            </div>
                            <div class="editor-field">
                                @Html.DropDownListFor(model => model.tipo, new List<SelectListItem>
                    {
                        new SelectListItem {Text = "Crédito", Value = "C"},
                        new SelectListItem {Text = "Débito", Value = "D"}
                    }, new { @class = "form-control", style = "width: 180px" })
                                @Html.ValidationMessageFor(model => model.tipo)
                            </div>
                        </div>
                        
                    </div>
                    <br />
                    <p>
                        <input type="button" name="Salvar" class="btn btn-primary" value="Salvar" data-toggle="modal" data-target="#myModal" /> | @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-primary" })
                    </p>
                    <div class="visibilidade">
                        @Html.LabelFor(model => model.id_operacao)
                    </div>
                    <div class="visibilidade">
                        @Html.EditorFor(model => model.id_operacao)
                        @Html.ValidationMessageFor(model => model.id_operacao)
                    </div>
                    <div class="modal fade" tabindex="-1" role="dialog" id="myModal">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title">ATENÇÃO</h4>
                                </div>
                                <div class="modal-body">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <span>Para esta operação, será necessário informar o idoso no lançamento de movimentos ?</span>
                                        </div>
                                    </div>
                                    
                                </div>
                                <div class="modal-footer">


                                    <input type="submit" name="Sim" class="btn btn-primary" value="Sim" />
                                    <input type="submit" name="Nao" class="btn btn-primary" value="Não" />



                                </div>
                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div><!-- /.modal -->
                </fieldset>
            </form>
        }
    </div>
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ASVP/Views/Operacao/Index.cshtml
@model IEnumerable<ASVP.Models.OPERACAO>
@{
    ViewBag.Title = "Index";
}


<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Cadastrar Operações</h3>
    </div>
    <div class="panel-body " style="overflow: auto">
        <p>
            <a href='@Url.Action("Create", "Operacao")'>
                <img src='@Url.Content("~/Images/adicionarOperacao.png")' />
            </a>
        </p>

        @if (ViewBag.Msg != null)
        {
            <div class="alert alert-danger">
                <strong>Atenção!</strong> @ViewBag.Msg
            </div>
        }
        <br />
        <table class="CSSTableGenerator">
            <tr>

                <th>
                    @Html.DisplayNameFor(model => model.descricao)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.tipo)
                </th>
                
                <th></th>
                <th></th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>

                    <td>
                        @Html.DisplayFor(modelItem => item.descricao)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.tipo)
                    </td>
                   
                    <td class="visibilidade">
                        @Html.DisplayFor(modelItem => item.id_operacao)
                    </td>
                    <td>
                        <a href='@Url.Action("Edit", "Operacao", new {id = item.id_operacao})'>
                            <img src='@Url.Content("~/Images/edit.png")' title="Editar" />
                        </a>

                        <a href='@Url.Action("Delete", "Operacao", new { id = item.id_operacao })'>
                            <img src='@Url.Content("~/Images/delete.png")' title="Excluir" />
                        </a>
                    </td>
                </tr>
            }
        </table>

    </div>
    </div>

    