ASVP/Controllers/BancoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ASVP.Models;

namespace ASVP.Controllers
{
    public class BancoController : Controller
    {
        private AsiloEntities db = new AsiloEntities();

        //
        // GET: /Banco/

        public ActionResult Index()
        {
            try
            {
                if (VerificaLoginBanco())
                {
                    return View(db.BANCO.OrderBy(p => p.nome).ToList());
                }
                else
                {
                    TempData["alertMessage"] = "Você precisa de permissão para acessar a tela de bancos.";
                    return RedirectToAction("Index", "Home", TempData["alertMessage"]);
                }
            }
            catch (Exception e)
            {

                ViewBag.Msg = e.Message;
                return View();
            }
            
        }

       

        //
        // GET: /Banco/Details/5

        public ActionResult Details(int id = 0)
        {
            try
            {
                BANCO banco = db.BANCO.Find(id);
                if (banco == null)
                {
                    return HttpNotFound();
                }
                return View(banco);

            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
                return View();
            }
           
        }

        //
        // GET: /Banco/Create

        public ActionResult Create()
        {
            try
            {
                if (VerificaLoginBanco())
                {

                    return View();
                }
                else
                {
                    TempData["alertMessage"] = "Você precisa de permissão para acessar a tela de bancos.";
                    return RedirectToAction("Index", "Home", TempData["alertMessage"]);
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
                return View();
            }
            
        }

        //
        // POST: /Banco/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BANCO banco)
        {
            try
            {
                if (VerificaLoginBanco())
                {
                    if (ModelState.IsValid)
                    {
                        banco.nome = banco.nome.ToUpper();
                        db.BANCO.Add(banco);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }

                    return View(banco);
                }
                else
                {
                    TempData["alertMessage"] = "Você precisa de permissão para acessar a tela de bancos.";
                    return RedirectToAction("Index", "Home", TempData["alertMessage"]);
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
                return View(banco);
            }
           
        }

        //
        // GET: /Banco/Edit/5

        public ActionResult Edit(int id)
        {
            try
            {
                if (VerificaLoginBanco())
                {
                    BANCO banco = db.BANCO.Find(id);
                    if (banco == null)
                    {
                        return HttpNotFound();
                    }
                    return View(banco);
                }
                else
                {
                    TempData["alertMessage"] = "Você precisa de permissão para acessar a tela de bancos.";
                    return RedirectToAction("Index", "Home", TempData["alertMessage"]);
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
                return View();
            }
           
        }

        //
        // POST: /Banco/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(BANCO banco)
        {
            try
            {
                if (VerificaLoginBanco())
                {
                    if (ModelState.IsValid)
                    {
                        banco.nome = banco.nome.ToUpper();
                        db.Entry(banco).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    return View(banco);
                }
                else
                {
                    TempData["alertMessage"] = "Você precisa de permissão para acessar a tela de bancos.";
                    return RedirectToAction("Index", "Home", TempData["alertMessage"]);
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
                return View(banco);
            }
            
        }

        //
        // GET: /Banco/Delete/5

        public ActionResult Delete(int id)
        {
            try
            {
                if (VerificaLoginBanco())
                {
                    BANCO banco = db.BANCO.Find(id);
                    if (banco == null)
                    {
                        return HttpNotFound();
                    }
                    return View(banco);
                }
                else
                {
                    TempData["alertMessage"] = "Você precisa de permissão para acessar a tela de bancos.";
                    return RedirectToAction("Index", "Home", TempData["alertMessage"]);
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
                return View();
            }
            
        }

        //
        // POST: /Banco/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                if (VerificaLoginBanco())
                {
                    BANCO banco = db.BANCO.Find(id);
                    db.BANCO.Remove(banco);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["alertMessage"] = "Você precisa de permissão para acessar a tela de bancos.";
                    return RedirectToAction("Index", "Home", TempData["alertMessage"]);
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
                return View();
            }
           
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public bool VerificaLoginBanco()
        {

            if (Request.Cookies["usuarioAsilo"] != null)
            {
                int id = Convert.ToInt32(Request.Cookies["usuarioAsilo"].Value.ToString().Replace("usuarioAsilo=", ""));
                if (db.ADMINISTRADOR.Find(id).cadBanco == "S")
                    return true;
                else return false;
            }
            else
            {
                return false;

            }
        }
    }
}

ASVP/Controllers/IdosoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ASVP.Models;
using PagedList;
using iTextSharp.text.pdf;
using iTextSharp.text;
using System.IO;
using System.ComponentModel;

namespace ASVP.Controllers
{
    public class IdosoController : Controller
    {
        private AsiloEntities db = new AsiloEntities();

        //
        // GET: /Idoso/

        public ActionResult Index(string idoso, int? pagina, string filtroExcel, string tipoRelatorio)
        {

            try
            {
                if (VerificaLoginIdoso())
                {
                    int tamanhoPagina = 10;
                    int numeroPagina = pagina ?? 1;

                    ViewBag.idoso = idoso;

                    var ListaIdoso = db.IDOSO.Where(p => p.nome == idoso).OrderBy(p => p.nome).ToList();

                    if (tipoRelatorio != null)
                    {
                        if (tipoRelatorio == "Beneficios")
                        {
                            var beneficios = db.BENEFICIO_IDOSO.Include(p => p.IDOSO)
                            .Select(g => new EXPORT_BENEFICIOS
                            {
                                nome = g.IDOSO.nome,
                                cpf = g.IDOSO.cpf,
                                rg = g.IDOSO.rg,
                                pai = g.IDOSO.pai,
                                mae = g.IDOSO.mae,
                                num_beneficio = g.numBeneficio,
                                nNit = g.nNit
                            }).OrderBy(p => p.nome).ToList();

                            ExportBeneficios(beneficios);
                        }
                        else
                        {
                            if (filtroExcel != null)
                                if (filtroExcel != "")
                                    Export(db.IDOSO.OrderBy(p => p.nome).ToList(), filtroExcel);
                        }

                    }

                    if (idoso != null && idoso != "")
                        return View(ListaIdoso.Where(p => p.dataObito == null).ToPagedList(numeroPagina, tamanhoPagina));
                    else
                    {
                        return View(db.IDOSO.Where(p => p.dataObito == null).OrderBy(p => p.nome).ToList().ToPagedList(numeroPagina, tamanhoPagina));
                    }


                }
                else
                {
                    TempData["alertMessage"] = "Você precisa de permissão para acessar a tela de idosos.";
                    return RedirectToAction("Index", "Home", TempData["alertMessage"]);
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
                return View();

            }


        }

        private void Export(List<IDOSO> idosos, string filtroExcel)
        {
            try
            {
                if (VerificaLoginIdoso())
                {
                    foreach (var item in idosos)
                    {

                    }
                    Response.ClearContent();
                    Response.AddHeader("content-disposition",
                        "attachment;filename=Idosos" +
                        DateTime.Now.ToShortDateString().Replace("/", "").Replace("-", "") + ".xls");
                    Response.AddHeader("Content-Type", "application/vnd.ms-excel");
                    WriteTsv(idosos, Response.Output, filtroExcel);
                    Response.End();

                    // return RedirectToAction("Index");
                }
                else
                {

                    TempData["alertMessage"] = "Você precisa de permissão para acessar a consulta de movimentos.";
                    // return RedirectToAction("Index", "Home", TempData["alertMessage"]);
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
                //return View(idosos);

            }


        }

        private void ExportBeneficios(List<EXPORT_BENEFICIOS> beneficios)
        {
            try
            {
                if (VerificaLoginIdoso())
                {
                    foreach (var item in beneficios)
                    {

                    }
                    Response.ClearContent();
                    Response.AddHeader("content-disposition",
                        "attachment;filename=Beneficios" +
                        DateTime.Now.ToShortDateString().Replace("/", "").Replace("-", "") + ".xls");
                    Response.AddHeader("Content-Type", "application/vnd.ms-excel");
                    WriteTsvBeneficios(beneficios, Response.Output);
                    Response.End();

                    // return RedirectToAction("Index");
                }
                else
                {

                    TempData["alertMessage"] = "Você precisa de permissão para acessar a consulta de movimentos.";
                    // return RedirectToAction("Index", "Home", TempData["alertMessage"]);
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
                //return View(idosos);

            }


        }


        //GERA PLANILHA EXCEL
        public void WriteTsv<T>(IEnumerable<T> data, TextWriter output, string filtroExcel)
        {
            try
            {
                PropertyDescriptorCollection props = TypeDescriptor.GetProperties(typeof(T));
                foreach (PropertyDescriptor prop in props)
                {
                    for (int i = 0; i < filtroExcel.Split(',').Length; i++)
                    {
                        if (prop.DisplayName.ToUpper() == filtroExcel.Split(',')[i].Split('-')[0])
                        {
                            output.Write(prop.DisplayName.ToUpper()); // header
                            output.Write("\t");
                        }
                    }

                }
                output.WriteLine();
                foreach (T item in data)
                {
                    foreach (PropertyDescriptor prop in props)
                    {
                        for (int i = 0; i < filtroExcel.Split(',').Length; i++)
                        {
                            if (prop.DisplayName.ToUpper() == filtroExcel.Split(',')[i].Split('-')[0])
                            {
                                output.Write(removeCE(prop.Converter.ConvertToString(prop.GetValue(item))));
                                output.Write("\t");
                            }
                        }

                    }
                    output.WriteLine();
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;


            }

        }

        //GERA PLANILHA EXCEL
        public void WriteTsvBeneficios<T>(IEnumerable<T> data, TextWriter output)
        {
            try
            {
                PropertyDescriptorCollection props = TypeDescriptor.GetProperties(typeof(T));
                foreach (PropertyDescriptor prop in props)
                {
                    output.Write(prop.DisplayName); // header
                    output.Write("\t");
                }
                output.WriteLine();
                foreach (T item in data)
                {
                    foreach (PropertyDescriptor prop in props)
                    {
                        output.Write(removeCE(prop.Converter.ConvertToString(prop.GetValue(item))));
                        output.Write("\t");
                    }
                    output.WriteLine();
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;


            }

        }



        private String removeCE(String str)
        {
            try
            {
                str = str.Replace("Á", "A").Replace("Â", "A").Replace("À", "A")
                        .Replace("Ã", "A").Replace("Ä", "A");
                str = str.Replace("á", "a").Replace("â", "a").Replace("à", "a")
                        .Replace("ã", "a").Replace("ä", "a");
                str = str.Replace("É", "E").Replace("Ê", "E").Replace("È", "E");
                str = str.Replace("é", "e").Replace("ê", "e").Replace("è", "e");
                str = str.Replace("Í", "I").Replace("Î", "I").Replace("Ì", "I")
                        .Replace("Ï", "I");
                str = str.Replace("í", "i").Replace("î", "i").Replace("ì", "i")
                        .Replace("ï", "i");
                str = str.Replace("Ó", "O").Replace("Ô", "O").Replace("Ò", "O")
                        .Replace("Õ", "O");
                str = str.Replace("ó", "o").Replace("ô", "o").Replace("ò", "o")
                        .Replace("õ", "o");
                str = str.Replace("Ú", "U").Replace("Ü", "U");
                str = str.Replace("ú", "u").Replace("ü", "u");
                str = str.Replace("Ç", "C").Replace("ç", "c");

                return str;
            }
            catch (Exception ex)
            {
                return "";
                // MessageBox.Show(")
            }
        }

        public ActionResult TagSearch(string term)
        {
            try
            {
                // Get Tags from database
                var idosos = db.IDOSO.Select(p => p.nome).ToList().Where(t => t.ToUpper().StartsWith(term.ToString().ToUpper()));
                return this.Json(idosos,
                                JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;

                return null;
            }

        }

        //
        // GET: /Idoso/Details/5

        public ActionResult Details(int id = 0)
        {

            try
            {

ASVP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - ASILO SÃO VICENTE DE PAULO</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/themes/base/css")
    @Scripts.Render("~/bundles/modernizr")

    @*<link href="~/bootstrap-3.2.0-dist/css/bootstrap.css" rel="stylesheet" />


        <link href="~/bootstrap-3.2.0-dist/css/bootstrap-theme.css" rel="stylesheet" />*@
    <link href="~/bootstrap-3.3.6-dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/bootstrap-3.3.6-dist/css/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/bootstrap-3.3.6-dist/css/table.css" rel="stylesheet" />
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <script type="text/javascript">
        function MascaraMoeda(objTextBox, SeparadorMilesimo, SeparadorDecimal, e) {
            var sep = 0;
            var key = '';
            var i = j = 0;
            var len = len2 = 0;
            var strCheck = '0123456789';
            var aux = aux2 = '';
            var whichCode = (window.Event) ? e.which : e.keyCode;
            if (whichCode == 13 || whichCode == 8 || whichCode == 0) return true;
            key = String.fromCharCode(whichCode); // Valor para o código da Chave
            if (strCheck.indexOf(key) == -1) return false; // Chave inválida
            len = objTextBox.value.length;
            for (i = 0; i < len; i++)
                if ((objTextBox.value.charAt(i) != '0') && (objTextBox.value.charAt(i) != SeparadorDecimal)) break;
            aux = '';
            for (; i < len; i++)
                if (strCheck.indexOf(objTextBox.value.charAt(i)) != -1) aux += objTextBox.value.charAt(i);
            aux += key;
            len = aux.length;
            if (len == 0) objTextBox.value = '';
            if (len == 1) objTextBox.value = '0' + SeparadorDecimal + '0' + aux;
            if (len == 2) objTextBox.value = '0' + SeparadorDecimal + aux;
            if (len > 2) {
                aux2 = '';
                for (j = 0, i = len - 3; i >= 0; i--) {
                    if (j == 3) {
                        aux2 += SeparadorMilesimo;
                        j = 0;
                    }
                    aux2 += aux.charAt(i);
                    j++;
                }
                objTextBox.value = '';
                len2 = aux2.length;
                for (i = len2 - 1; i >= 0; i--)
                    objTextBox.value += aux2.charAt(i);
                objTextBox.value += SeparadorDecimal + aux.substr(len - 2, len);
            }
            return false;
        }

        //Para controlar o Scroll da pagina//////////////////////////////////////////////////
        ///////////////////////////////////////////////////////////////////////
        window.onscroll = scroll;

        function scroll() {
            var myPageX;
            var myPageY;
            //IE
            if (document.all) {
                myPageX = document.documentElement.scrollLeft;
                myPageY = document.documentElement.scrollTop;
            }
                //Firefox,Opera,Chrome
            else {
                myPageX = window.pageXOffset;
                myPageY = window.pageYOffset;
            }

            document.getElementById("lblScrool").value = myPageY;
            gravaCookie(myPageY);

        }

        function gravaCookie(Y) {
            var dtmData = new Date();
            var lngDias = 1;
            if (lngDias) {
                dtmData.setTime(dtmData.getTime() + 10000)

                var strExpira = "; expires=" + dtmData.toGMTString();
            } else {
                var strExpira = "";
            }
            document.cookie = 'PagePosition' + "=" + Y + strExpira;
        }

        function reloadPage() {
            var posicao = LerCookie('PagePosition');
            if (posicao != null) {
                self.scrollTo(0, posicao);
            }
        }


        function LerCookie(strCookie) {
            var strNomeIgual = strCookie + "=";
            var arrCookies = document.cookie.split(';');

            for (var i = 0; i < arrCookies.length; i++) {
                var strValorCookie = arrCookies[i];
                while (strValorCookie.charAt(0) == ' ') {
                    strValorCookie = strValorCookie.substring(1, strValorCookie.length);
                }
                if (strValorCookie.indexOf(strNomeIgual) == 0) {
                    return strValorCookie.substring(strNomeIgual.length, strValorCookie.length);
                }
            }
            return null;

        }
        //////////////////////
    </script>

    <style type="text/css">
        th {
            text-align: center;
        }
    </style>


</head>
<body onload="reloadPage();">
    <header>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">
                    <img src='@Url.Content("~/Images/asilo_logo.png")' /> SISTEMA INTEGRADO ASVP
                </p>

            </div>
            <div class="float-left">

                <nav id="myNavbar" class="navbar navbar-default" role="navigation">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="container">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>

                        </div>

                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" style="font-weight: bold" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav">
                                <li>@Html.ActionLink("Home", "Index", "Home")</li>

                                <li class="dropdown">
                                    <a href="#" data-toggle="dropdown" class="dropdown-toggle">Cadastros <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li>@Html.ActionLink("Idosos", "Index", "Idoso")</li>
                                        <li>@Html.ActionLink("Operações", "Index", "Operacao")</li>
                                        <li>@Html.ActionLink("Destinos", "Index", "Destino")</li>
                                        <li>@Html.ActionLink("Bancos", "Index", "Banco")</li>
                                    </ul>
                                </li>
                                <li class="dropdown">
                                    <a href="#" data-toggle="dropdown" class="dropdown-toggle">Lançamentos<b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li>@Html.ActionLink("Movimentos", "Create", "Movimento")</li>

                                    </ul>
                                </li>
                                @*<li class="dropdown">
                                        <a href="#" data-toggle="dropdown" class="dropdown-toggle">Consultas<b class="caret"></b></a>
                                        <ul class="dropdown-menu">
                                            <li>@Html.ActionLink("Relatório Sintético", "RelSintetico", "Movimento")</li>
                                            <li>@Html.ActionLink("Relatório Análítico", "Index", "Movimento")</li>


                                        </ul>
                                    </li>*@
                                <li class="dropdown">
                                    <a href="#" data-toggle="dropdown" class="dropdown-toggle">Consultas<b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li>@Html.ActionLink("Movimentos", "Index", "Movimento")</li>
                                        <li>@Html.ActionLink("Capa do Caixa", "RelCaixa", "Movimento")</li>
                                    </ul>
                                </li>

                                <li>@Html.ActionLink("Configurações", "Index", "Administrador")</li>
                            </ul>

                            <ul class="nav navbar-nav navbar-right">

                                <li>
                                    <p>
                                        <a href='@Url.Action("Logout", "Login")'>
                                            <img src='@Url.Content("~/Images/logoff.png")' title="Sair" />
                                        </a>
                                    </p>
                                </li>
                            </ul>

                        </div><!-- /.navbar-collapse -->
                    </div>
                </nav>
            </div>
        </div>




    </header>
    <div class="container-fluid">
        <div id="body" onload="reloadPage();">


            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
    </div>

    <footer>
        <label id="lblScrool" for="lblScrool"></label>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year - ASVP</p>
            </div>
        </div>
    </footer>


    <script src="~/Scripts/jquery.min.js"></script>

    <!-- Bootstrap -->
    <!-- Include all compiled plugins (below), or include individual files as needed -->


    <script src="~/bootstrap-3.3.6-dist/js/bootstrap.min.js"></script>
    @*@Scripts.Render("~/bundles/jquery")*@

    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")


    <script src="~/Scripts/jquery.maskMoney.js"></script>
    <script src="~/Scripts/jquery.maskedinput.js"></script>

    @RenderSection("scripts", required: false)


</body>
</html>

ASVP/Views/Shared/_Layout1.cshtml
@RenderBody()