ASVP/Controllers/DestinoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ASVP.Models;

namespace ASVP.Controllers
{
    public class DestinoController : Controller
    {
        private AsiloEntities db = new AsiloEntities();

        //
        // GET: /Destino/

        public ActionResult Index()
        {
            try
            {
                if (VerificaLoginDestino())
                {
                    return View(db.DESTINO.OrderBy(p=>p.descricao).ToList());
                }
                else
                {
                    TempData["alertMessage"] = "Você precisa de permissão para acessar a tela de destinos.";
                    return RedirectToAction("Index", "Home", TempData["alertMessage"]);
                }

            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
                return View();

            }
        }

       
        //
        // GET: /Destino/Details/5

        public ActionResult Details(int id)
        {
            try
            {
                if (VerificaLoginDestino())
                {
                    DESTINO destino = db.DESTINO.Find(id);
                    if (destino == null)
                    {
                        return HttpNotFound();
                    }
                    return View(destino);
                }
                else
                {
                    TempData["alertMessage"] = "Você precisa de permissão para acessar a tela de destinos.";
                    return RedirectToAction("Index", "Home", TempData["alertMessage"]);
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
                return View();

            }

        }

        //
        // GET: /Destino/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Destino/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DESTINO destino)
        {
            try
            {
                if (VerificaLoginDestino())
                {
                    if (ModelState.IsValid)
                    {
                        destino.descricao = destino.descricao.ToUpper();
                        db.DESTINO.Add(destino);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }

                    return View(destino);
                }
                else
                {
                    TempData["alertMessage"] = "Você precisa de permissão para acessar a tela de destinos.";
                    return RedirectToAction("Index", "Home", TempData["alertMessage"]);
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
                return View(destino);

            }
        }

        //
        // GET: /Destino/Edit/5

        public ActionResult Edit(int id)
        {
            try
            {
                if (VerificaLoginDestino())
                {
                    DESTINO destino = db.DESTINO.Find(id);
                    if (destino == null)
                    {
                        return HttpNotFound();
                    }
                    return View(destino);
                }
                else
                {
                    TempData["alertMessage"] = "Você precisa de permissão para acessar a tela de destinos.";
                    return RedirectToAction("Index", "Home", TempData["alertMessage"]);
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
                return View();

            }
        }

        //
        // POST: /Destino/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(DESTINO destino)
        {
            try
            {
                if (VerificaLoginDestino())
                {
                    if (ModelState.IsValid)
                    {
                        destino.descricao = destino.descricao.ToUpper();
                        db.Entry(destino).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    return View(destino);
                }
                else
                {
                    TempData["alertMessage"] = "Você precisa de permissão para acessar a tela de destinos.";
                    return RedirectToAction("Index", "Home", TempData["alertMessage"]);
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
                return View(destino);

            }
        }

        //
        // GET: /Destino/Delete/5

        public ActionResult Delete(int id)
        {
            try
            {
                if (VerificaLoginDestino())
                {
                    DESTINO destino = db.DESTINO.Find(id);
                    if (destino == null)
                    {
                        return HttpNotFound();
                    }
                    return View(destino);
                }
                else
                {
                    TempData["alertMessage"] = "Você precisa de permissão para acessar a tela de destinos.";
                    return RedirectToAction("Index", "Home", TempData["alertMessage"]);
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
                return View();

            }
        }

        //
        // POST: /Destino/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

            try
            {
                if (VerificaLoginDestino())
                {
                    DESTINO destino = db.DESTINO.Find(id);
                    db.DESTINO.Remove(destino);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                else
                {
                    TempData["alertMessage"] = "Você precisa de permissão para acessar a tela de destinos.";
                    return RedirectToAction("Index", "Home", TempData["alertMessage"]);
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
                return View();

            }
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public bool VerificaLoginDestino()
        {

            if (Request.Cookies["usuarioAsilo"] != null)
            {
                int id = Convert.ToInt32(Request.Cookies["usuarioAsilo"].Value.ToString().Replace("usuarioAsilo=", ""));
                if (db.ADMINISTRADOR.Find(id).cadDestino == "S")
                    return true;
                else return false;
            }
            else
            {
                return false;

            }
        }
    }
}

ASVP/Views/Destino/Create.cshtml
@model ASVP.Models.DESTINO

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
    $(document).ready(function () { $("#descricao").addClass("text-uppercase"); });
   
</script>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Novo Destino</h3>
    </div>
    <div class="panel-body">
        @if (ViewBag.Msg != null)
        {
            <div class="alert alert-danger">
                <strong>Atenção!</strong> @ViewBag.Msg
            </div>
        }
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            <fieldset>
                <legend>DESTINO</legend>

                <div class="row">
                    
                    <div class="col-lg-4">
                        <div class="editor-label">
                            @Html.LabelFor(model => model.descricao)
                        </div>
                        <div class="editor-field">
                            @Html.EditorFor(model => model.descricao)
                            @Html.ValidationMessageFor(model => model.descricao)
                        </div>
                    </div>

                </div>
                <p>
                    <input type="submit" name="Salvar" class="btn btn-primary" value="Salvar" /> | @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-primary" })
                </p>
            </fieldset>
        }

    </div>
</div>


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ASVP/Views/Destino/Delete.cshtml
@model ASVP.Models.DESTINO

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (Model != null) { 
    <h3>Tem certeza que deseja apagar o destino @Model.descricao ?</h3>
}
<br />
@if (ViewBag.Msg != null)
{
    <div class="alert alert-danger">
        <strong>Atenção!</strong> @ViewBag.Msg
    </div> 
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Sim" class="btn btn-primary" />
        @Html.ActionLink("Não", "Index", null, new { @class = "btn btn-primary" })
    </p>

    <div class="visibilidade">
        @Html.DisplayNameFor(model => model.idDestino)
    </div>
    <div class="visibilidade">
        @Html.DisplayFor(model => model.idDestino)
    </div>
}
          
    </p>

ASVP/Views/Destino/Details.cshtml
@model ASVP.Models.DESTINO

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<fieldset>
    <legend>DESTINO</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.idDestino)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.idDestino)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.descricao)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.descricao)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id=Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ASVP/Views/Destino/Edit.cshtml
@model ASVP.Models.DESTINO

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
    $(document).ready(function () { $("#descricao").addClass("text-uppercase"); });

</script>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Editar Destino @Model.descricao</h3>
    </div>
    <div class="panel-body">
        @if (ViewBag.Msg != null)
        {
            <div class="alert alert-danger">
                <strong>Atenção!</strong> @ViewBag.Msg
            </div>
        }
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            <fieldset>
                <legend>DESTINO</legend>

                <div class="row">
                    
                    <div class="col-lg-3">
                        <div class="editor-label">
                            @Html.LabelFor(model => model.descricao)
                        </div>
                        <div class="editor-field">
                            @Html.EditorFor(model => model.descricao)
                            @Html.ValidationMessageFor(model => model.descricao)
                        </div>
                    </div>
                    <div class="col-lg-3 visibilidade">
                        <div class="editor-label">
                            @Html.LabelFor(model => model.idDestino)
                        </div>
                        <div class="editor-field">
                            @Html.EditorFor(model => model.idDestino)
                            @Html.ValidationMessageFor(model => model.idDestino)
                        </div>
                    </div>

                </div>
                <br />
                <p>
                    <input type="submit" name="Salvar" class="btn btn-primary" value="Salvar" /> | @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-primary" })
                </p>
            </fieldset>
        }

    </div>
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ASVP/Views/Destino/Index.cshtml
@model IEnumerable<ASVP.Models.DESTINO>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Cadastrar Destino</h3>
    </div>
    <div class="panel-body " style="overflow: auto">

        <p>
            <a href='@Url.Action("Create", "Destino")'>
                <img src='@Url.Content("~/Images/destino.png")' />
            </a>
        </p>
        <table class="CSSTableGenerator">
            <tr>
               
                <th>
                    @Html.DisplayNameFor(model => model.descricao)
                </th>
                <th></th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                   
                    <td>
                        @Html.DisplayFor(modelItem => item.descricao)
                    </td>
                    <th class="visibilidade">@Html.DisplayFor(modelItem => item.idDestino)</th>
                    <td>
                        <a href='@Url.Action("Edit", "Destino", new {id = item.idDestino})'>
                            <img src='@Url.Content("~/Images/edit.png")' title="Editar" />
                        </a>

                        <a href='@Url.Action("Delete", "Destino", new { id = item.idDestino })'>
                            <img src='@Url.Content("~/Images/delete.png")' title="Excluir" />
                        </a>
                    </td>
                </tr>
            }

        </table>
    </div>

</div>