ASVP/Controllers/BancoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ASVP.Models;

namespace ASVP.Controllers
{
    public class BancoController : Controller
    {
        private AsiloEntities db = new AsiloEntities();

        //
        // GET: /Banco/

        public ActionResult Index()
        {
            try
            {
                if (VerificaLoginBanco())
                {
                    return View(db.BANCO.OrderBy(p => p.nome).ToList());
                }
                else
                {
                    TempData["alertMessage"] = "Você precisa de permissão para acessar a tela de bancos.";
                    return RedirectToAction("Index", "Home", TempData["alertMessage"]);
                }
            }
            catch (Exception e)
            {

                ViewBag.Msg = e.Message;
                return View();
            }
            
        }

       

        //
        // GET: /Banco/Details/5

        public ActionResult Details(int id = 0)
        {
            try
            {
                BANCO banco = db.BANCO.Find(id);
                if (banco == null)
                {
                    return HttpNotFound();
                }
                return View(banco);

            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
                return View();
            }
           
        }

        //
        // GET: /Banco/Create

        public ActionResult Create()
        {
            try
            {
                if (VerificaLoginBanco())
                {

                    return View();
                }
                else
                {
                    TempData["alertMessage"] = "Você precisa de permissão para acessar a tela de bancos.";
                    return RedirectToAction("Index", "Home", TempData["alertMessage"]);
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
                return View();
            }
            
        }

        //
        // POST: /Banco/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BANCO banco)
        {
            try
            {
                if (VerificaLoginBanco())
                {
                    if (ModelState.IsValid)
                    {
                        banco.nome = banco.nome.ToUpper();
                        db.BANCO.Add(banco);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }

                    return View(banco);
                }
                else
                {
                    TempData["alertMessage"] = "Você precisa de permissão para acessar a tela de bancos.";
                    return RedirectToAction("Index", "Home", TempData["alertMessage"]);
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
                return View(banco);
            }
           
        }

        //
        // GET: /Banco/Edit/5

        public ActionResult Edit(int id)
        {
            try
            {
                if (VerificaLoginBanco())
                {
                    BANCO banco = db.BANCO.Find(id);
                    if (banco == null)
                    {
                        return HttpNotFound();
                    }
                    return View(banco);
                }
                else
                {
                    TempData["alertMessage"] = "Você precisa de permissão para acessar a tela de bancos.";
                    return RedirectToAction("Index", "Home", TempData["alertMessage"]);
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
                return View();
            }
           
        }

        //
        // POST: /Banco/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(BANCO banco)
        {
            try
            {
                if (VerificaLoginBanco())
                {
                    if (ModelState.IsValid)
                    {
                        banco.nome = banco.nome.ToUpper();
                        db.Entry(banco).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    return View(banco);
                }
                else
                {
                    TempData["alertMessage"] = "Você precisa de permissão para acessar a tela de bancos.";
                    return RedirectToAction("Index", "Home", TempData["alertMessage"]);
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
                return View(banco);
            }
            
        }

        //
        // GET: /Banco/Delete/5

        public ActionResult Delete(int id)
        {
            try
            {
                if (VerificaLoginBanco())
                {
                    BANCO banco = db.BANCO.Find(id);
                    if (banco == null)
                    {
                        return HttpNotFound();
                    }
                    return View(banco);
                }
                else
                {
                    TempData["alertMessage"] = "Você precisa de permissão para acessar a tela de bancos.";
                    return RedirectToAction("Index", "Home", TempData["alertMessage"]);
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
                return View();
            }
            
        }

        //
        // POST: /Banco/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                if (VerificaLoginBanco())
                {
                    BANCO banco = db.BANCO.Find(id);
                    db.BANCO.Remove(banco);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["alertMessage"] = "Você precisa de permissão para acessar a tela de bancos.";
                    return RedirectToAction("Index", "Home", TempData["alertMessage"]);
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
                return View();
            }
           
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public bool VerificaLoginBanco()
        {

            if (Request.Cookies["usuarioAsilo"] != null)
            {
                int id = Convert.ToInt32(Request.Cookies["usuarioAsilo"].Value.ToString().Replace("usuarioAsilo=", ""));
                if (db.ADMINISTRADOR.Find(id).cadBanco == "S")
                    return true;
                else return false;
            }
            else
            {
                return false;

            }
        }
    }
}

ASVP/Controllers/MovimentoController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using ASVP.Models;
using System.Data.Objects.SqlClient;
using PagedList;
using DotNet.Highcharts.Options;
using DotNet.Highcharts.Helpers;
using DotNet.Highcharts;
using DotNet.Highcharts.Enums;
using System.Drawing;
using System.Globalization;
using iTextSharp.text;
using iTextSharp.text.pdf;


namespace ASVP.Controllers
{
    public class MovimentoController : Controller
    {
        private AsiloEntities db = new AsiloEntities();

        //
        // GET: /Movimento/


        public ActionResult Index(string dataInicio, string dataFim, string TipoOperacao, string id_operacao, string idoso, string order, string pesquisaData,
 string id_banco, int? pagina, string pgtoEfetuado, string pgtoAberto, string idDestino, string grafico, string legenda)
        {
            try
            {
                if (VerificaLoginConsMovimento())
                {

                    int tamanhoPagina = 40;
                    int numeroPagina = pagina ?? 1;


                    int dias = DateTime.DaysInMonth(DateTime.Now.Year, DateTime.Now.Month);
                    if (dataInicio == null && dataFim == null)
                    {
                        dataInicio = "01" + "/" + DateTime.Now.Month.ToString().PadLeft(2, '0') + "/" +
                                     DateTime.Now.Year.ToString();
                        dataFim = dias.ToString().PadLeft(2, '0') + "/" + DateTime.Now.Month.ToString().PadLeft(2, '0') +
                                  "/" + DateTime.Now.Year.ToString();
                    }


                    var movimentacoes = db.MOVIMENTO.Include(m => m.IDOSO).Include(m => m.OPERACAO).Include(m => m.BANCO).Include(m => m.DESTINO);
                    var saldoAtual = db.MOVIMENTO.Include(m => m.IDOSO).Include(m => m.OPERACAO).Include(m => m.BANCO);

                    #region Filtros


                    
                    

                    if (id_banco != null)
                    {

                        if (id_banco != "")
                        {
                            int banco = Convert.ToInt32(id_banco);
                            movimentacoes = movimentacoes.Where(p => p.id_banco == banco);
                        }

                    }

                    if (TipoOperacao != null)
                    {
                        if (TipoOperacao.Trim() != "tipo")
                        {

                            movimentacoes = movimentacoes.Where(p => p.OPERACAO.tipo == TipoOperacao);
                        }
                    }
                    if (id_operacao != null)
                    {
                        if (id_operacao != "")
                        {
                            int idOperacao = Convert.ToInt32(id_operacao);
                            movimentacoes = movimentacoes.Where(p => p.id_operacao == idOperacao);

                        }

                    }
                    if (idDestino != null)
                    {
                        if (idDestino != "")
                        {
                            int idDest = Convert.ToInt32(idDestino);
                            movimentacoes = movimentacoes.Where(p => p.idDestino == idDest);

                        }

                    }
                    if (idoso != null)
                    {
                        if (idoso != "")
                        {
                            int codigoidoso = Convert.ToInt32(idoso.Split('-')[0]);

                            IDOSO ObjIdoso = db.IDOSO.First(p => p.id_idoso == codigoidoso);
                            movimentacoes = movimentacoes.Where(p => p.id_idoso == ObjIdoso.id_idoso);

                        }

                    }
                    if (TipoOperacao != null)
                    {
                        if (TipoOperacao.Trim() != "tipo")
                            ViewBag.id_operacao = new SelectList(db.OPERACAO.Where(p => p.tipo == TipoOperacao).OrderBy(p => p.descricao),
                                "id_operacao", "descricao");
                        else
                        {
                            ViewBag.id_operacao = new SelectList(db.OPERACAO.OrderBy(p => p.descricao), "id_operacao", "descricao");
                        }
                    }
                    else
                    {
                        ViewBag.id_operacao = new SelectList(db.OPERACAO.OrderBy(p => p.descricao), "id_operacao", "descricao");

                    }


                    saldoAtual = movimentacoes.Where(p => p.dataPgto != null); ;


                    ViewBag.pgtoAberto = pgtoAberto;
                    if (pgtoAberto != null)
                    {
                        if (pgtoAberto.Equals("on"))
                        {

                            ViewBag.pgtoAberto = "checked";
                            movimentacoes = movimentacoes.Where(p => p.dataPgto == null);
                            order = "vencimento";
                        }

                    }

                    ViewBag.pgtoEfetuado = pgtoEfetuado;
                    if (pgtoEfetuado != null)
                    {
                        if (pgtoEfetuado.Equals("on"))
                        {

                            ViewBag.pgtoEfetuado = "checked";
                            movimentacoes = movimentacoes.Where(p => p.dataPgto != null);
                            order = "vencimento";
                        }

                    }

                    if (dataInicio != "" && dataFim != "")
                    {
                        if (dataInicio.Trim().Length > 1 && dataFim.Trim().Length > 1)
                        {
                            DateTime dtInicio = Convert.ToDateTime(dataInicio).Date;
                            DateTime dtFim = Convert.ToDateTime(dataFim).Date;
                            if (pesquisaData == null)
                                pesquisaData = "vencimento";
                            if (pesquisaData == "pagamento")
                                movimentacoes = movimentacoes.Where(p => EntityFunctions.TruncateTime(p.dataPgto) >= dtInicio.Date && EntityFunctions.TruncateTime(p.dataPgto) <= dtFim.Date);
                            else
                            {
                                if (pesquisaData == "vencimento")
                                    movimentacoes = movimentacoes.Where(p => EntityFunctions.TruncateTime(p.dataVenc) >= dtInicio.Date && EntityFunctions.TruncateTime(p.dataVenc) <= dtFim.Date);

                            }
                        }

                    }
                    else
                    {
                        if ((dataInicio != "" && dataFim == "") || (dataInicio == "" && dataFim != ""))
                            ViewBag.Msg = "Por favor preencha a data de início e data final";
                    }


                    if (order != null)
                    {
                        if (order.Trim().Equals("vencimento"))
                            movimentacoes = movimentacoes.OrderBy(p => p.dataVenc).ThenBy(x => x.valor);
                        if (order.Trim().Equals("operacao"))
                            movimentacoes = movimentacoes.OrderBy(p => p.id_operacao);
                        if (order.Trim().Equals("valor"))
                            movimentacoes = movimentacoes.OrderBy(p => p.valor);
                        if (order.Trim().Equals("pagamento"))
                            movimentacoes = movimentacoes.OrderBy(p => p.dataPgto);
                        if (order.Trim().Equals("banco"))
                            movimentacoes = movimentacoes.OrderBy(p => p.BANCO.nome);
                        if (order.Trim().Equals("destino"))
                            movimentacoes = movimentacoes.OrderBy(p => p.DESTINO.descricao);

                    }
                    else
                    {
                        movimentacoes = movimentacoes.OrderBy(p => p.dataVenc).ThenBy(x => x.dataPgto).ThenBy(x => x.valor);
                    }

                    #endregion


                    var totalCredito = saldoAtual.Where(p => p.OPERACAO.tipo == "C").Sum(p => p.valor);
                    var totalDebito = saldoAtual.Where(p => p.OPERACAO.tipo == "D").Sum(p => p.valor);

                    ViewBag.totalCredito = totalCredito;
                    ViewBag.totalDebito = totalDebito;



                    #region Variaveis de pesquisa - ViewBags
                    ViewBag.SaldoAtual = saldoAtual;
                    ViewBag.idoso = idoso;
                    ViewBag.dataInicio = dataInicio;
                    ViewBag.dataFim = dataFim;
                    ViewBag.TipoOperacao = TipoOperacao;
                    ViewBag.order = order;
                    ViewBag.pesquisaData = pesquisaData;
                    ViewBag.OperacaoID = id_operacao;
                    ViewBag.BancoID = id_banco;
                    ViewBag.pgtoAberto = pgtoAberto;
                    ViewBag.pgtoEfetuado = pgtoEfetuado;
                    ViewBag.DestinoID = idDestino;
                    ViewBag.tipoGrafico = grafico;
                    ViewBag.legenda = legenda;
                    #endregion

                    ViewBag.id_banco = new SelectList(from p in db.BANCO
                                                      select new
                                                      {
                                                          id_banco = p.id_banco,
                                                          nome = (p.nome + "-" + p.conta).Trim()

ASVP/Views/Movimento/Create.cshtml
@using System.Runtime.InteropServices
@using System.Web.UI.WebControls
@using ASVP.Models

@model ASVP.Models.MOVIMENTO

@{
    ViewBag.Title = "Create";
}

<style type="text/css">
    .Negativo {
        color: red;
    }

    .Positivo {
        color: blue;
    }
</style>


<script type="text/javascript">

    $(document).ready(function () { $("#dataPgto").mask("99/99/9999"); });
    $(document).ready(function () { $("#dataVenc").mask("99/99/9999"); });


    $(function () {

        $("#dataPgto").datepicker({
            dateFormat: "dd/mm/yy", showOtherMonths: true,
            selectOtherMonths: true,
            dayNames: ["Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado", "Domingo"],
            dayNamesMin: ["D", "S", "T", "Q", "Q", "S", "S", "D"],
            dayNamesShort: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb", "Dom"],
            monthNames: ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"],
            monthNamesShort: ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez"],
            showAnim: "scale"
        });

        $("#dataVenc").datepicker({
            dateFormat: "dd/mm/yy", showOtherMonths: true,
            selectOtherMonths: true,
            dayNames: ["Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado", "Domingo"],
            dayNamesMin: ["D", "S", "T", "Q", "Q", "S", "S", "D"],
            dayNamesShort: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb", "Dom"],
            monthNames: ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"],
            monthNamesShort: ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez"],
            showAnim: "scale"
        });

        $("#valor").blur(function (event) {
            this.value = this.value.replace('.', '');
        });

    });

    //function ListarMovimentos() {
    //    $.ajax({ type: 'GET', url: '/Movimento/ListarMovimentos', dataType: 'html', cache: false, async: true, success: function (data) { $('#listarMovimentos').html(data); } });
    //}
    ////$(document).ready(function () { setInterval(atualizarDefinicao, 30000); });

    //window.onload = function () {
    //    // códigos JavaScript a serem executados quando a página carregar
    //    ListarMovimentos();
    //}

    $(function () {
        $("#valor").maskMoney();
    });
    $(document).ready(function () {
        $('#IDOSO_nome').autocomplete(
        {
            source: '@Url.Action("TagSearch", "Movimento")'
        });


    });

    function change_url(val) {

        //var url = "/Movimento/Create?TipoOperacao=" + val;
        var url = "/ASVP/Movimento/Create?TipoOperacao=" + val;
        window.location = url;


    }

    $('#dataVenc').change(function () {
        if (document.getElementById("dataVenc").value.length > 10)
            document.getElementById("dataVenc").value = document.getElementById("dataVenc").value.substring(0, 10);

    });
</script>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Nova movimentação</h3>
    </div>
    <div class="panel-body">

        @if (ViewBag.Msg != null)
        {
            <div class="alert alert-danger">
                <strong>Atenção!</strong> @ViewBag.Msg
            </div>
        }
        @if (ViewBag.MsgSucesso != null)
        {
            <div class="alert alert-success">
                <strong>Sucesso!</strong> @ViewBag.MsgSucesso
            </div>
        }
        <div class="row">
            <div class="col-md-12">


                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)

                    <form class="form-inline">
                        <fieldset>
                            <legend>MOVIMENTO</legend>

                            <div class="row">

                                <div class="col-md-2">
                                    <div class="editor-label">
                                        @Html.LabelFor(model => model.OPERACAO.tipo, "Tipo Operação")
                                    </div>
                                    <div class="editor-field">
                                        @{var listItems = new List<ListItem>
                                  {
                                      new ListItem {Text = "Selecione", Value = "tipo"},
                                      new ListItem {Text = "Despesa", Value = "D"},
                                      new ListItem {Text = "Receita", Value = "C"}
                                  }; }

                                        @Html.DropDownList("TipoOperacao", new SelectList(listItems, "Value", "Text"), new { @class = "form-control", onchange = "change_url(this.options[this.selectedIndex].value)" })
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="col-md-3" style="padding:0px">

                                        <div class="editor-label">
                                            @Html.LabelFor(model => model.id_operacao, "Operação")
                                        </div>
                                    </div>
                                    <div class="col-md-2" style="padding:0px">
                                        <a href='@Url.Action("Create", "Operacao")'>
                                            <img src='@Url.Content("~/Images/add.png")' />
                                        </a>
                                    </div>
                                    <div class="editor-field">

                                        @if (ViewBag.id_operacao != null)
                                        {
                                            @Html.DropDownList("id_operacao", new SelectList(ViewBag.id_operacao, "Value", "Text"), "Selecione", new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.id_operacao)
                                        }
                                        else
                                        {
                                            var operacoes = new List<ListItem>
                                          {
                                              new ListItem {Text = "Escolha uma operação...", Value = "operacao"}
                                          };
                                            @Html.DropDownList("id_operacao", new SelectList(operacoes, "Value", "Text"), new { @class = "form-control" })

                                        }

                                    </div>
                                </div>

                                <div class="col-md-6" style="padding:0px">
                                    <div class="col-md-6">
                                        <div class="col-md-3" style="padding:0px">

                                            <div class="editor-label">
                                                @Html.LabelFor(model => model.idDestino, "Destino")
                                            </div>
                                        </div>
                                        <div class="col-md-2" style="padding:0px">
                                            <a href='@Url.Action("Create", "Destino")'>
                                                <img src='@Url.Content("~/Images/add.png")' />
                                            </a>
                                        </div>
                                        <div class="editor-field">
                                            @if (ViewBag.idDestino != null)
                                            {@Html.DropDownList("idDestino", new SelectList(ViewBag.idDestino, "Value", "Text"), "Selecione", new { @class = "form-control" })}
                                        </div>


                                    </div>

                                    <div class="col-md-6">
                                        <div class="col-md-3" style="padding:0px">

                                            <div class="editor-label">
                                                @Html.LabelFor(model => model.id_banco, "Conta")
                                            </div>
                                        </div>
                                        <div class="col-md-2" style="padding:0px">
                                            <a href='@Url.Action("Create", "Banco")'>
                                                <img src='@Url.Content("~/Images/add.png")' />
                                            </a>
                                        </div>
                                        <div class="editor-field">
                                            @if (ViewBag.id_banco != null)
                                            {@Html.DropDownList("id_banco", new SelectList(ViewBag.id_banco, "Value", "Text"), "Selecione", new { @class = "form-control" })}
                                        </div>


                                    </div>
                                </div>




                            </div>

                            <div class="row" style="padding-top: 10px;">

                                <div class="col-md-6">
                                    <div class="editor-label">
                                        @Html.LabelFor(model => model.IDOSO.nome)
                                    </div>
                                    <div class="form-group">
                                        <div class="input-group">
                                            @Html.TextBoxFor(model => model.IDOSO.nome, new { @class = "form-control", placeholder = "Informe o nome do idoso" })

                                            <div class="input-group-addon">
                                                <img src="~/Images/oldman.png" />
                                            </div>
                                        </div>
                                    </div>


                                </div>


                                <div class="col-md-2">
                                    <div class="editor-label">
                                        @Html.LabelFor(model => model.dataVenc)
                                    </div>
                                    <div class="editor-field">

                                        @Html.EditorFor(model => model.dataVenc)


                                    </div>

                                </div>

                                <div class="col-md-2">
                                    <div class="editor-label">
                                        @Html.LabelFor(model => model.dataPgto)
                                    </div>
                                    <div class="editor-field">
                                        @Html.EditorFor(model => model.dataPgto)

                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="editor-label">
                                        @Html.LabelFor(model => model.valor)
                                    </div>
                                    <div class="editor-field">
                                        @Html.EditorFor(model => model.valor)
                                        @Html.ValidationMessageFor(model => model.valor)
                                    </div>
                                </div>



                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="editor-label">
                                        @Html.LabelFor(model => model.obs)
                                    </div>
                                    <div class="editor-field">
                                        @Html.TextAreaFor(model => model.obs, new { @class = "text-uppercase" })
                                        @Html.ValidationMessageFor(model => model.obs)
                                    </div>
                                </div>

                            </div>

                            <div class="row">
                                <div class="col-lg-12">
                                    <input type="submit" name="Salvar" class="btn btn-primary" value="Salvar" />  @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-primary", type = "button" })
                                </div>

                            </div>
                        </fieldset>
                    </form>

                }
            </div>
        </div>


        <div id="listaMovimentos">
            <div class="row">

                @{
                    Html.RenderPartial("ListarMovimentos", Model.listaMovimentos);
                }
            </div>
        </div>



    </div>

</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ASVP/Views/Movimento/Delete.cshtml
@model ASVP.Models.MOVIMENTO

@{
    ViewBag.Title = "Delete";
}

<h2>Excluir Movimentação</h2>

<h3>Você tem certeza que deseja excluir esta movimentação do dia @Html.DisplayFor(model => model.dataMov), no valor de R$ @Html.DisplayFor(model => model.valor)?</h3>
@if (ViewBag.Msg != null)
{
    <div class="alert alert-danger">
        <strong>Atenção!</strong> @ViewBag.Msg
    </div>
}
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Excluir" name="Excluir" class="btn btn-primary" /> | @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-primary", type = "button" })
    </p>
}

ASVP/Views/Movimento/GraficoCredito.cshtml
@model DotNet.Highcharts.Highcharts
@{
    ViewBag.Title = "GraficoCredito";
}
<script src="~/Scripts/Highcharts-3.0.1/js/highcharts.js"></script>

@Model